Snailedlt/improve build changes
Panquesito7/devicon pull request #187
Opened 2023-03-23 09:56 UTC by Snailedlt

@Panquesito7 I couldn't get the local SVG icons to show up. Neither on my branch, nor on yours. The font seems to work fine though.

Please test if you're able to, since I wasn't able to get it working locally

2023-03-23 10:20 UTC, Snailedlt commented
Maybe the reason it's failing is that building the icons with windows instructions doesn't work, so I had to build using `npm run build-icons` instead
![image](https://user-images.githubusercontent.com/43886029/227173310-3122841d-dde2-4e00-91b4-956d7e0c678f.png)

2023-03-23 11:40 UTC, Snailedlt commented
@Panquesito7 It works with the files @lunatic-fox shared here: https://github.com/devicons/devicon/pull/1668#issuecomment-1481022111

2023-04-07 19:00 UTC, Panquesito7 requested changes

2023-04-07 21:29 UTC, Snailedlt commented on docs/index.html
> -          addCss(`${baseUrl}devicon.min.css`);
I don't think so because iirc it worked just fine with the icons that lunatic built for me. So the issue seems to be the build script, and not the markup itself

Did you get time to test the branch btw?

2023-04-13 21:49 UTC, Panquesito7 commented on docs/index.html
> -          addCss(`${baseUrl}devicon.min.css`);
Nope, I haven't tested. Will test it right away and let you know how it works. 🙂

2023-04-14 03:38 UTC, Panquesito7 commented
Seems to be working pretty well. All icons showed up (using Gitpod, preferred way).

![image](https://user-images.githubusercontent.com/51391473/231935265-7703a451-5ec7-4856-b14c-b445d3ec6fbe.png)

2023-04-14 11:08 UTC, Snailedlt commented
@Panquesito7 neat!
Vould you also test locally please?

If it works locally for you, please send me some instructions, cause we might need to edit the readme then

2023-04-21 14:11 UTC, Panquesito7 approved these changes
Thanks! This is much simpler and better. 🚀

2023-04-21 14:39 UTC, merged